services:

  db:
    image: mysql:8.4
    container_name: banco-mysql

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sistema

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: backend-login

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: