
# Defina a imagem base que será utilizada para construir o backend.
# Considere uma imagem oficial do Node.js.
# Pesquise as diferenças entre as versões disponíveis e suas variantes.


# Defina o diretório de trabalho dentro do container.
# Os próximos comandos deverão utilizar esse diretório como referência.


# Copie os arquivos necessários para instalação das dependências.
# Considere utilizar o package.json e o package-lock.json.


# Execute a instalação das dependências da aplicação.


# Copie os demais arquivos do projeto para dentro da imagem.


# Informe qual porta será utilizada pela aplicação dentro do container.


# Defina o comando que será executado quando o container iniciar.
# Considere utilizar o script de inicialização definido no package.json.
